name: Deploy VuePress

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20 

      - name: Install dependencies
        run: npm install

      - name: Fix permissions for VuePress
        run: chmod +x node_modules/.bin/vuepress node_modules/.bin/vuepress-vite node_modules/.bin/vuepress-cli

      - name: Build VuePress
        run: npx vuepress build docs --clean-cache

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: docs/.vuepress/dist
